version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      working_dir: /app
      volumes:
        - .:/app
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=adminpass
        - POSTGRES_DB=game
      ports:
        - "8084:5432"

    webserver:
      image: nginx:alpine
      working_dir: /app
      volumes:
          - .:/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    rabbitmq:
      build: phpdocker/rabbitmq
      ports:
        - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin

    php-fpm:
      build: ./phpdocker/php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

