# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
      resource: '../src/*'
      exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    ### UI
    App\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    App\Application\Command\Fight\AskForFightMessageHandler:
        tags:
          name: messenger.message_handler
          handles: App\Application\Command\Fight\AskForFightCommand
    App\Application\Command\Score\WriteScoreFightMessageHandler:
      tags:
        name: messenger.message_handler
        handles: App\Application\Command\Score\WriteScoreFightCommand

imports:
  - { resource: commands.yml }
  - { resource: repositories.yml }
  - { resource: queries.yml }